### ISSUE TITLE
Add a usage example

### ISSUE THREAD

**Issue by excieve** [isindir/eks-ebs-node-operator#14]
Just found this operator while researching the node volume limit issue in the EBS CSI, but not quite sure how to use it.

As I understand it sets the `eks/attachments/EBS` resource limit on each node based of its instance type. I can observe this after installing the operator into the cluster. However, I'm not sure how to make use of this limit now?

Would be great to have an example in the readme.

**Comment by isindir** [comment]
Hi @excieve, please see example in the updated readme.

**Comment by excieve** [comment]
Thanks for a quick reply @isindir! I've already tried this, but I get the following error when trying to apply this resource to a pod:
```
# * spec.containers[0].resources.limits[eks/attachments/EBS]: Invalid value: "eks/attachments/EBS": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
# * spec.containers[0].resources.limits[eks/attachments/EBS]: Invalid value: "eks/attachments/EBS": doesn't follow extended resource name standard
```

**Comment by excieve** [comment]
Judging by the `IsQualifiedName` function in k8s `apimachinery` package, which throws this error, `eks/attachments/EBS` indeed shouldn't pass validation as it expects either none or one `/`:
https://github.com/kubernetes/apimachinery/blob/76330795f827e44ffc47f4fdc8e0d39872bead8f/pkg/util/validation/validation.go#L42
